{% set name = "promise" %}
{% set version = "2.3" %}
{% set sha256 = "dfd18337c523ba4b6a58801c164c1904a9d4d1b1747c7d5dbf45b693a49d93d0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - six
    - typing  # [py<35]

test:
  imports:
    - promise

about:
  home: https://github.com/syrusakbary/promise
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Ultra-performant Promise implementation in Python'
  description: |
      This is a implementation of Promises in Python. It is a super set of
      Promises/A+ designed to have readable, performant code and to provide
      just the extensions that are absolutely necessary for using promises in
      Python.  Its fully compatible with the Promises/A+ spec
  doc_url: https://github.com/syrusakbary/promise
  dev_url: https://github.com/syrusakbary/promise

extra:
  recipe-maintainers:
    - dfroger
    - pmlandwehr
