travis:
  secure:
    BINSTAR_TOKEN: PpzeK6d4fPyl345BWLUnXpo6ePc8W255SueQP9VtdDEakVjYNNbW2b2Xei+oASSas3wQbbg2PkDBXUCgTD/iZvM+I4lCLx6sCSfuyqI0poS0NcDc4cs20eYy2NdcWWiIKZ7gz92ZQZ+3VTIHUu9P7vMU8jOPe8qA169PFeKjs1WmgUDyH3H8P1zAzM+xGorgtLibM0t6c48DbIldhXbNYOLbOqF7c1a3dCHZ7woTVYzqAVyibQ7URq4spZaEN80igIJIb12/M3euowvVBEuGwOHkNHtrJE3dktfZon0VWvcLLk1Xxm7/SN/48ufCYE6Cgt0W3irqCf2UgfDT8FZ4Ntd9a86iKsBU3rif8sX13BqOMaJsfqAo61b0qkW8X08MnDhT0i4UFr+dw5pg9Z9cDX/k3eztcCAK4GCmF5x7fzAEJCJD16Nw+50tKAlwrGcR0TYZfikeVmMH+e8IEGgNnbNCXxtJBqJI8A2k5YXFuPOK6QkoseogXWx11fllp5lsLeBKdft1S0tX4jnoh8Diav1lntTB+B3bAn2LTTBtYp7tJDSjieNAvh5FaRPreqwQgRlJrGUvbBHdUJlLtAio5fFgpq3Hid5pIsBztIrIGn+sR3N65dmweDulkXnaP69+mUeqeTBEDAODEY5k6PIm5U+0Eeonyuc+bvvjtMhxomQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
